// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmyhacwngsvrdeircygw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhteWhhY3duZ3N2cmRlaXJjeWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDk1MDQsImV4cCI6MjA2OTc4NTUwNH0.srbYv0MYbpvwpQIaaBnvi6yrBi_YRWCUtuHh30sKA6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});